---
title: "IS381 Statistics and Probability with R"
tbl-colwidths: [10,10,20,5,5,5,5,5,5,5]
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source('config.R')
```

This page contains an outline of the topics, content, and assignments for the semester.
Note that this schedule will be updated as the semester progresses.

**Meetups will be held on `r class_day` from `r class_time`. [Click here to join the meetup](https://us02web.zoom.us/j/81437953852?pwd=Q9bNGwoair9WGOtb4dBsI6cdi5QHUI.1).**


```{r, echo=FALSE, results='asis'}
slides_uri <- '/slides/'

# icons::download_fontawesome()

column_mapping <- list(
	Prepare = icons::fontawesome('readme'),
	# Slides = icons::fontawesome('chalkboard-teacher'),
	Video = icons::fontawesome('youtube'),
	Homework = icons::fontawesome('edit'),
	Lab = icons::fontawesome('flask')
)

options(knitr.kable.NA = '')
schedule <- readxl::read_excel('Schedule.xlsx') |> as.data.frame()
# icons::download_fontawesome()

# schedule$Start <- format(schedule$Start, '%a, %b %d')

video_rows <- which(!is.na(schedule$Video))
if(length(video_rows) > 0) {
	schedule[video_rows,]$Video <- paste0('https://youtu.be/', schedule[video_rows,]$Video)
}

slides <- !is.na(schedule$Slides)
if(sum(slides) > 0) {
	slide_links <- paste0(
		'<a href="', slides_uri, schedule[slides,]$Slides, '.html" target="_blank" style="text-decoration:none;">',
		icons::fontawesome('safari'), '</a>',
		'&nbsp;&nbsp;',
		'<a href="', slides_uri, schedule[slides,]$Slides, '.pdf" target="_blank" style="text-decoration:none;">',
		icons::fontawesome('file-pdf'), '</a>'
	)
	slide_links <- gsub('\\n', '', slide_links)
	schedule[slides,]$Slides <- slide_links
}

for(i in names(column_mapping)) {
	if(i %in% names(schedule)) {
		links <- !is.na(schedule[,i,drop=TRUE])
		if(sum(links) > 0) {
			schedule[links,i] <- paste0(
				' <a href="', schedule[links,i,drop=TRUE], '">',
				column_mapping[[i]],
				'</a>'
			)
		}
	}
}

# schedule <- schedule |> dplyr::select(!c(StartTime, EndTime))
schedule |>
	knitr::kable(format = 'html',
				 escape = FALSE, 
				 align = c('c', 'l', 'l', 'l', 'l', rep('c', ncol(schedule) - 5))) |>
	kableExtra::column_spec(column = which(names(schedule) == 'Topic'),
							width_min = '300px') |>
	# kableExtra::column_spec(column = which(names(schedule) == 'Start'),
	# 						width_min = '100px') |>
	kableExtra::column_spec(column = which(names(schedule) %in% names(column_mapping)),
							width_max = '50px') # Not sure this is working
```


